name: Prettier on pull requests

on:
  pull_request:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v4.3
        with:
          dry: true
